//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine_Art.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public int S_Id { get; set; }
        public Nullable<int> C_Id { get; set; }
        public string Award_Title { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Student Student { get; set; }
    }
}
