//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine_Art.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int E_Id { get; set; }
        public string Event_Detail { get; set; }
        public string DateTime { get; set; }
        public string Country { get; set; }
    }
}
