//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fine_Art.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibition
    {
        public string Painting_Pic { get; set; }
        public string Painting_Detail { get; set; }
        public Nullable<int> Price { get; set; }
        public string Status { get; set; }
        public Nullable<int> E_Id { get; set; }
        public Nullable<int> S_Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
